title: JavaScript Anywhere
subtitle: JSAnywhere
devices:
  phone: iPhone
  pad: iPad

locales:
  en:
    lead: In a moment of inspiration.
    faq: FAQ
    mail: E-mail
    help: Help
  ja:
    lead: そのひらめき、忘れないうちに
    faq: よくある質問
    mail: メール
    help: ヘルプ
